---
- name: Update netbox directories
  ansible.builtin.file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: directory
    recurse: true
  loop:
    - env
  become: "{{ netbox_become }}"

- name: Update environment files
  ansible.builtin.template:
    src: "env/{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/env/{{ item }}"
    mode: "0644"
  loop:
    - netbox.env
    - postgres.env
    - redis-cache.env
    - redis.env
  become: "{{ netbox_become }}"
  notify: Restart netbox

- name: Update configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ netbox_base_dir }}/{{ item }}"
    mode: "0644"
  loop:
    - docker-compose.yml
    - extra.py
  become: "{{ netbox_become }}"
  notify: Restart netbox

- name: Update container mounts
  ansible.builtin.copy:
    src: nginx-unit.json
    dest: "{{ netbox_base_dir }}/nginx-unit.json"
    mode: "0644"
  become: "{{ netbox_become }}"
  notify: Restart netbox

- name: Remove outdated files
  ansible.builtin.file:
    path: "{{ netbox_base_dir }}/{{ item }}"
    state: absent
  loop:
    - netbox.env
    - configuration/configuration.py
    - configuration/gunicorn_config.py
  become: "{{ netbox_become }}"

- name: Flush handlers
  meta: flush_handlers

- name: Ensure netbox is running
  uri:
    url: "{{ netbox_url }}"
    follow_redirects: none
  register: netbox_url_results
  until: netbox_url_results.status == 200
  retries: 20
  delay: 5
  check_mode: False

